"""db

Revision ID: 2cf2319369fd
Revises: 8acfa5a7901c
Create Date: 2024-11-15 16:06:17.850490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf2319369fd'
down_revision = '8acfa5a7901c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backed_projects', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'rewards', ['reward_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('backed_projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
