"""new_db

Revision ID: 928e6486dc81
Revises: 38f41e6f57ba
Create Date: 2024-11-16 01:55:55.656006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928e6486dc81'
down_revision = '38f41e6f57ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backed_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backed_projects', schema=None) as batch_op:
        batch_op.drop_column('donation_amount')

    # ### end Alembic commands ###
